version '3.8'

services
  app
    build 
      context .
      dockerfile Dockerfile
    container_name laravel_app
    volumes
      - .varwwwhtml
    ports
      - 808080
    depends_on
      - db
    networks
      - laravel_network

  db
    image postgreslatest
    container_name postgres_db
    environment
      POSTGRES_USER laravel_user
      POSTGRES_PASSWORD secret
      POSTGRES_DB laravel_db
    volumes
      - postgres_datavarlibpostgresqldata
    ports
      - 54325432
    networks
      - laravel_network

  pgadmin
    image dpagepgadmin4latest
    container_name pgadmin
    environment
      PGADMIN_DEFAULT_EMAIL admin@example.com
      PGADMIN_DEFAULT_PASSWORD admin
    ports
      - 505080
    depends_on
      - db
    networks
      - laravel_network

networks
  laravel_network

volumes
  postgres_data
